### ISSUE TITLE
HACS?

### ISSUE THREAD

**Issue by felipecrs** [chomupashchuk/empty-service-home-assistant#2]
It would be super cool if this could be added to HACS, to simplify the installation. :-)

**Comment by chomupashchuk** [comment]
After component creation there were multiple features introduced, which make this component less useful with time. Making it HACS compatible requires updates of another 2 repositories maintained by other people, restructuring this one and creation of icons of different size. It seems like to much work while very few people actually use this component.

**Comment by felipecrs** [comment]
Ok, thank you anyway!
